version: "3"
services:
  # redis:
  #   image: redis
  #   ports:
  #     - 6379:6379
  #   volumes:
  #     - "/usr/local/var/myapp:/data"
  #   deploy:
  #     placement:
  #       constraints: [node.role == manager]
  #   command: redis-server --appendonly yes
  mysql:
    image: mysql:5.7
    environment:
        - MYSQL_ROOT_PASSWORD=admin
        - MYSQL_DATABASE=liriklagu
    volumes:
      - /usr/local/var/liriklagu/mysql:/var/lib/mysql
    ports:
      - 3306:3306
  adminer:
    image: adminer
    restart: always
    ports:
      - 9090:8080
